name: ci
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-gomod-

      - name: Verify formatting
        run: |
          out=$(gofmt -l .)
          if [ -n "$out" ]; then
            echo "$out"; echo "Run gofmt on the files above"; exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: make test
